version: "3.9"

networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config:

services:
  php:
    image: ghcr.io/eventpoints/kontractpoint.com-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database
    restart: unless-stopped
    environment:
      MERCURE_PUBLIC_URL: "https://kontractpoint.com/.well-known/mercure"
      APP_ENV: "prod"
      DATABASE_URL: "postgresql://__KONTRACTPOINT_POSTGRES_USER__:__KONTRACTPOINT_POSTGRES_PASSWORD__@database:5432/__KONTRACTPOINT_POSTGRES_DBNAME__?serverVersion=13&charset=utf8"
      MERCURE_JWT_SECRET: "__KONTRACTPOINT_MERCURE_JWT_SECRET__"
      APP_SECRET: "__KONTRACTPOINT_APP_SECRET__"
      MAILER_DSN: "__KONTRACTPOINT_MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__KONTRACTPOINT_MESSENGER_TRANSPORT_DSN__"
      APP_TIMEZONE: "__KONTRACTPOINT_APP_TIMEZONE__"
      CORS_ALLOW_ORIGIN: "__KONTRACTPOINT_CORS_ALLOW_ORIGIN__"
      CLOUDFLARE_TURNSTILE_PUBLIC_KEY: "__KONTRACTPOINT_CLOUDFLARE_TURNSTILE_PUBLIC_KEY__"
      CLOUDFLARE_TURNSTILE_PRIVATE_KEY: "__KONTRACTPOINT_CLOUDFLARE_TURNSTILE_PRIVATE_KEY__"
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/kontractpoint.com-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__KONTRACTPOINT_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__KONTRACTPOINT_MERCURE_JWT_SECRET__"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kontractpoint.rule=Host(`kontractpoint.com`, `www.kontractpoint.com`)"
      - "traefik.http.routers.kontractpoint.tls=true"
      - "traefik.http.routers.kontractpoint.tls.certresolver=le"
    networks:
      - traefik
      - internal

  asset-mapper-compile:
    image: ghcr.io/eventpoints/php:main
    platform: linux/amd64
    volumes:
      - .:/app:cached
    working_dir: /app
    entrypoint: [ "" ]
    command: "bash -c 'bin/console importmap:compile'"

  tailwind-build:
    image: ghcr.io/eventpoints/php:main
    platform: linux/amd64
    volumes:
      - .:/app:cached
    working_dir: /app
    entrypoint: [ "" ]
    command: "bash -c 'bin/console tailwind:build --minify'"

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__KONTRACTPOINT_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__KONTRACTPOINT_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__KONTRACTPOINT_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kontractpoint-adminer.rule=Host(`adminer.kontractpoint.com`)"
      - "traefik.http.routers.kontractpoint-adminer.tls=true"
      - "traefik.http.routers.kontractpoint-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik
